### ISSUE TITLE
Issue with login and web session 

### ISSUE THREAD

**Issue by gilles33377** [Juraji/image-manager-2#9]
**Describe the bug**
Hello, when i install the soft , i can't retreive my boards.

**To Reproduce**
Steps to reproduce the behavior: (Use a virtual machine to reproduce the problem if you don't want to break something)
1. Install chrome + java latest version
2. Log on pinterest (you can use google login or normal login) and save
3. click on add pinterest board
4. nothing happens (chrome supposed to open ?)

**Expected behavior**
I can retreive the boards and download the images

**Screenshots**
proof that i was logged
![im1](https://user-images.githubusercontent.com/27515067/58819442-889c2f00-8630-11e9-8d0e-b4bce23ade91.JPG)

**Desktop (please complete the following information):**
 - OS:  Windows 
 - Version :  10/7

**Additional context**
When i use the cmd to open the jar file  with --debug command :  it works and open chrome to work

SAME THING on every versions of IM.

**Any idea to solve ?**
I see the other issues and :

Chrome don't remind the account because the soft use a specific profile ? (i tried to sync my account on chrome but when i log in, my profile don't show in)

The soft don't use the cookie that chrome created ?

**I wanted to say thanks for your soft anyway. You saved a lot of my time**

**Here is the log txt without the debug command**

> 
> 18:39:38.995 [JavaFX Application Thread] INFO  io.ebean.config.properties.LoadContext: loaded properties from [ebean.properties]
> 18:39:39.070 [JavaFX Application Thread] INFO  io.ebean.EbeanVersion: ebean version: 11.38.1
> 18:39:39.188 [JavaFX Application Thread] INFO  io.ebean.datasource.pool.ConnectionPool: DataSourcePool [db] autoCommit[false] transIsolation[READ_COMMITTED] min[2] max[200]
> 18:39:39.356 [JavaFX Application Thread] INFO  io.ebean.internal.DefaultContainer: DatabasePlatform name:db platform:h2
> 18:39:39.611 [JavaFX Application Thread] INFO  io.ebean.migration.MigrationRunner: local migrations:7  existing migrations:7  checkState:false
> 18:39:42.436 [JavaFX Application Thread] INFO  nl.juraji.imagemanager.fxml.dialogs.WorkDialog: Executing task "Fetching Pinterest boards..."
> 18:39:43.464 [pool-3-thread-1] INFO  io.github.bonigarcia.wdm.WebDriverManager: Using chromedriver 74.0.3729.6 (since Google Chrome 74 is installed in your machine)
> 18:39:43.476 [pool-3-thread-1] INFO  io.github.bonigarcia.wdm.WebDriverManager: Exporting webdriver.chrome.driver as .\chromedriver\win32\74.0.3729.6\chromedriver.exe
> 18:39:43.507 [pool-3-thread-1] INFO  nl.juraji.imagemanager.util.io.web.WebDriverPool: Driver instance requested
> 18:39:48.912 [pool-3-thread-1] INFO  nl.juraji.imagemanager.util.io.web.WebDriverPool: Driver instance available: 22f277c2ac75c030d850f9de8ba76ac7
> 18:39:48.915 [pool-3-thread-1] INFO  nl.juraji.imagemanager.tasks.pinterest.FetchPinterestBoardsTask: Initializing driver for https://pinterest.com
> 18:39:52.592 [pool-3-thread-1] INFO  nl.juraji.imagemanager.tasks.pinterest.FetchPinterestBoardsTask: Driver: Not authenticated!
> 18:39:52.593 [pool-3-thread-1] ERROR nl.juraji.imagemanager.fxml.dialogs.WorkDialog: Error executing task
> nl.juraji.imagemanager.util.exceptions.ManagerTaskException: Not authenticated on Pinterest
> 	at nl.juraji.imagemanager.tasks.pinterest.PinterestWebTask.call(PinterestWebTask.java:76)
> 	at nl.juraji.imagemanager.tasks.pinterest.FetchPinterestBoardsTask.call(FetchPinterestBoardsTask.java:34)
> 	at nl.juraji.imagemanager.tasks.pinterest.FetchPinterestBoardsTask.call(FetchPinterestBoardsTask.java:24)
> 	at nl.juraji.imagemanager.fxml.dialogs.WorkDialog.lambda$exec$3(WorkDialog.java:131)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> 18:39:52.593 [pool-3-thread-1] INFO  nl.juraji.imagemanager.util.io.web.WebDriverPool: Driver instance returned 22f277c2ac75c030d850f9de8ba76ac7
> 18:39:55.334 [JavaFX Application Thread] INFO  nl.juraji.imagemanager.fxml.dialogs.WorkDialog: Executing task "Fetching Pinterest boards..."
> 18:39:55.349 [pool-4-thread-1] INFO  nl.juraji.imagemanager.util.io.web.WebDriverPool: Driver instance requested
> 18:39:55.355 [pool-4-thread-1] INFO  nl.juraji.imagemanager.util.io.web.WebDriverPool: Driver instance available: 22f277c2ac75c030d850f9de8ba76ac7
> 18:39:55.369 [pool-4-thread-1] INFO  nl.juraji.imagemanager.tasks.pinterest.FetchPinterestBoardsTask: Driver: Not authenticated!
> 18:39:55.370 [pool-4-thread-1] ERROR nl.juraji.imagemanager.fxml.dialogs.WorkDialog: Error executing task
> nl.juraji.imagemanager.util.exceptions.ManagerTaskException: Not authenticated on Pinterest
> 	at nl.juraji.imagemanager.tasks.pinterest.PinterestWebTask.call(PinterestWebTask.java:76)
> 	at nl.juraji.imagemanager.tasks.pinterest.FetchPinterestBoardsTask.call(FetchPinterestBoardsTask.java:34)
> 	at nl.juraji.imagemanager.tasks.pinterest.FetchPinterestBoardsTask.call(FetchPinterestBoardsTask.java:24)
> 	at nl.juraji.imagemanager.fxml.dialogs.WorkDialog.lambda$exec$3(WorkDialog.java:131)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> 18:39:55.370 [pool-4-thread-1] INFO  nl.juraji.imagemanager.util.io.web.WebDriverPool: Driver instance returned 22f277c2ac75c030d850f9de8ba76ac7
> 
> 
> 
> 
> 18:41:41.112 [JavaFX Application Thread] INFO  io.ebean.config.properties.LoadContext: loaded properties from [ebean.properties]
> 18:41:41.190 [JavaFX Application Thread] INFO  io.ebean.EbeanVersion: ebean version: 11.38.1
> 18:41:41.304 [JavaFX Application Thread] INFO  io.ebean.datasource.pool.ConnectionPool: DataSourcePool [db] autoCommit[false] transIsolation[READ_COMMITTED] min[2] max[200]
> 18:41:41.477 [JavaFX Application Thread] INFO  io.ebean.internal.DefaultContainer: DatabasePlatform name:db platform:h2
> 18:41:41.722 [JavaFX Application Thread] INFO  io.ebean.migration.MigrationRunner: local migrations:7  existing migrations:7  checkState:false
> 18:41:46.553 [JavaFX Application Thread] INFO  nl.juraji.imagemanager.fxml.dialogs.WorkDialog: Executing task "Authenticating on Pinterest..."
> 18:41:47.529 [pool-3-thread-1] INFO  io.github.bonigarcia.wdm.WebDriverManager: Using chromedriver 74.0.3729.6 (since Google Chrome 74 is installed in your machine)
> 18:41:47.536 [pool-3-thread-1] INFO  io.github.bonigarcia.wdm.WebDriverManager: Exporting webdriver.chrome.driver as .\chromedriver\win32\74.0.3729.6\chromedriver.exe
> 18:42:26.260 [pool-3-thread-1] INFO  nl.juraji.imagemanager.fxml.dialogs.WorkDialog: Completed task "Authenticating on Pinterest..."
> 18:42:32.472 [JavaFX Application Thread] INFO  nl.juraji.imagemanager.fxml.dialogs.WorkDialog: Executing task "Fetching Pinterest boards..."
> 18:42:32.589 [pool-5-thread-1] INFO  io.github.bonigarcia.wdm.WebDriverManager: Using chromedriver 74.0.3729.6 (since Google Chrome 74 is installed in your machine)
> 18:42:32.591 [pool-5-thread-1] INFO  io.github.bonigarcia.wdm.WebDriverManager: Exporting webdriver.chrome.driver as .\chromedriver\win32\74.0.3729.6\chromedriver.exe
> 18:42:32.623 [pool-5-thread-1] INFO  nl.juraji.imagemanager.util.io.web.WebDriverPool: Driver instance requested
> 18:42:37.660 [pool-5-thread-1] INFO  nl.juraji.imagemanager.util.io.web.WebDriverPool: Driver instance available: d52be944a5703ead9cf675993d5d1773
> 18:42:37.664 [pool-5-thread-1] INFO  nl.juraji.imagemanager.tasks.pinterest.FetchPinterestBoardsTask: Initializing driver for https://pinterest.com
> 18:42:41.266 [pool-5-thread-1] INFO  nl.juraji.imagemanager.tasks.pinterest.FetchPinterestBoardsTask: Driver: Not authenticated!
> 18:42:41.267 [pool-5-thread-1] ERROR nl.juraji.imagemanager.fxml.dialogs.WorkDialog: Error executing task
> nl.juraji.imagemanager.util.exceptions.ManagerTaskException: Not authenticated on Pinterest
> 	at nl.juraji.imagemanager.tasks.pinterest.PinterestWebTask.call(PinterestWebTask.java:76)
> 	at nl.juraji.imagemanager.tasks.pinterest.FetchPinterestBoardsTask.call(FetchPinterestBoardsTask.java:34)
> 	at nl.juraji.imagemanager.tasks.pinterest.FetchPinterestBoardsTask.call(FetchPinterestBoardsTask.java:24)
> 	at nl.juraji.imagemanager.fxml.dialogs.WorkDialog.lambda$exec$3(WorkDialog.java:131)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> 18:42:41.267 [pool-5-thread-1] INFO  nl.juraji.imagemanager.util.io.web.WebDriverPool: Driver instance returned d52be944a5703ead9cf675993d5d1773
> 
>

**Comment by gilles33377** [comment]
Hello again, same thing but with a different error :

I tried everything but now i can't retreive my board even with debug.

Pinterest website is blank when i load it : 
> 
>java -jar "image-manager-2.0.3 (1).jar" --debug
22:36:28.457 [JavaFX Application Thread] INFO  io.ebean.config.properties.LoadContext: loaded properties from [ebean.properties]
22:36:28.464 [JavaFX Application Thread] INFO  io.ebean.EbeanVersion: ebean version: 11.38.1
22:36:28.524 [JavaFX Application Thread] INFO  io.ebean.datasource.pool.ConnectionPool: DataSourcePool [db] autoCommit[false] transIsolation[READ_COMMITTED] min[2] max[200]
22:36:28.653 [JavaFX Application Thread] INFO  io.ebean.internal.DefaultContainer: DatabasePlatform name:db platform:h2
22:36:28.881 [JavaFX Application Thread] INFO  io.ebean.migration.MigrationRunner: local migrations:7  existing migrations:7  checkState:false
22:36:31.950 [JavaFX Application Thread] INFO  nl.juraji.imagemanager.fxml.dialogs.WorkDialog: Executing task "Fetching Pinterest boards..."
22:36:32.648 [pool-3-thread-1] INFO  io.github.bonigarcia.wdm.WebDriverManager: Using chromedriver 76.0.3809.12 (since Google Chrome 76 is installed in your machine)
22:36:32.655 [pool-3-thread-1] INFO  io.github.bonigarcia.wdm.WebDriverManager: Exporting webdriver.chrome.driver as .\chromedriver\win32\76.0.3809.12\chromedriver.exe
22:36:32.736 [pool-3-thread-1] INFO  nl.juraji.imagemanager.util.io.web.WebDriverPool: Driver instance requested
Starting ChromeDriver 76.0.3809.12 (220b19a666554bdcac56dff9ffd44c300842c933-refs/branch-heads/3809@{#83}) on port 32602
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1560198996.028][WARNING]: Timed out connecting to Chrome, retrying...
juin 10, 2019 10:36:38 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFOS: Detected dialect: W3C
22:36:38.078 [pool-3-thread-1] INFO  nl.juraji.imagemanager.util.io.web.WebDriverPool: Driver instance available: d6c388a7f80145aa995fecb143095794
22:36:38.083 [pool-3-thread-1] INFO  nl.juraji.imagemanager.tasks.pinterest.FetchPinterestBoardsTask: Initializing driver for https://pinterest.com
22:36:43.366 [pool-3-thread-1] ERROR nl.juraji.imagemanager.fxml.dialogs.WorkDialog: Error executing task
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for presence of element located by: By.id: initial-state (tried for 2 second(s) with 500 milliseconds interval)
        at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
        at nl.juraji.imagemanager.tasks.pinterest.PinterestWebTask.getElementBy(PinterestWebTask.java:154)
        at nl.juraji.imagemanager.tasks.pinterest.PinterestWebTask.call(PinterestWebTask.java:80)
        at nl.juraji.imagemanager.tasks.pinterest.FetchPinterestBoardsTask.call(FetchPinterestBoardsTask.java:34)
        at nl.juraji.imagemanager.tasks.pinterest.FetchPinterestBoardsTask.call(FetchPinterestBoardsTask.java:24)
        at nl.juraji.imagemanager.fxml.dialogs.WorkDialog.lambda$exec$3(WorkDialog.java:131)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#initial\-state"}
  (Session info: chrome=76.0.3809.12)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-AHK4D1B', ip: '192.168.1.13', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 76.0.3809.12, chrome: {chromedriverVersion: 76.0.3809.12 (220b19a666554..., userDataDir: C:\Users\Gilles\AppData\Loc...}, goog:chromeOptions: {debuggerAddress: localhost:50233}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: d6c388a7f80145aa995fecb143095794
*** Element info: {Using=id, value=initial-state}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:372)
        at org.openqa.selenium.By$ById.findElement(By.java:188)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
        at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:182)
        at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:179)
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
        ... 10 common frames omitted
22:36:43.367 [pool-3-thread-1] INFO  nl.juraji.imagemanager.util.io.web.WebDriverPool: Driver instance returned d6c388a7f80145aa995fecb143095794
